const $ = s => document.querySelector(s);
const store = {get:(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)), set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const images={push:'assets/push.jpg',upper:'assets/band-upper.jpg',row:'assets/band-row.jpg',glute:'assets/glute.jpg',core:'assets/core.jpg'};
const ex=(name,sets,img,cues)=>({name,sets,img,cues});
const workouts={
  1:{title:'Грудь, плечи + пресс',sub:'Силовая • 50–60 минут',items:[ex('Классические отжимания','4 × 8–20','push',['Ладони под плечами, тело — прямая линия.','Опускайся грудью, не проваливай поясницу.']),ex('Отжимания с резинкой','3 × 6–15','push',['Лента проходит за верхом спины, концы фиксируются ладонями.','Сопротивление должно расти на подъёме.']),ex('Жим резинки над головой','3 × 10–15','upper',['Встань на середину ленты.','Не прогибай поясницу; напряги пресс и ягодицы.']),ex('Трицепс из-за головы','3 × 10–15 / рука','upper',['Наступи на ленту одной ногой.','Локоть направлен вверх и остаётся на месте.']),ex('Reverse crunch','3 × 12–20','core',['Подкручивай таз вверх, а не просто маши ногами.','Опускайся медленно.']),ex('Планка','3 × 35–60 сек','core',['Рёбра подтянуты, ягодицы напряжены.','Не поднимай и не проваливай таз.'])]},
  2:{title:'Ноги, ягодицы + кор',sub:'Без прыжков • бережно к коленям',items:[ex('Ягодичный мост','4 × 15–20','glute',['Толкайся пятками, вверху сожми ягодицы.','Не переразгибай поясницу.']),ex('Мост на одной ноге','3 × 8–12 / нога','glute',['Таз остаётся ровным.','Уменьши амплитуду, если тянет поясницу.']),ex('Румынская тяга с резинкой','4 × 10–15','glute',['Встань на ленту, таз веди назад.','Спина нейтральная, колени мягкие.']),ex('Вставание с высокого стула','3 × 8–15','glute',['Только без боли и в комфортной глубине.','Колени смотрят в сторону носков.']),ex('Подъёмы на носки','4 × 15–25','glute',['Полная контролируемая амплитуда.']),ex('Dead bug','3 × 10–12 / сторона','core',['Поясница не отрывается от пола.','Двигай противоположные руку и ногу медленно.']),ex('Боковая планка','3 × 25–45 сек / сторона','core',['Тело держит одну ровную линию.'])]},
  3:{title:'Спина, бицепс + пресс',sub:'Силовая • 50–60 минут',items:[ex('Тяга резинки сидя к поясу','4 × 12–20','row',['Середина ленты на стопах, спина вытянута.','Тяни локти к тазу и своди лопатки.']),ex('Тяга резинки в наклоне','4 × 10–15','row',['Встань на ленту, наклонись тазом назад.','Не округляй спину и не пожимай плечами.']),ex('Pull-apart','3 × 15–25','row',['Разводи ленту до сведения лопаток.','Плечи не поднимай к ушам.']),ex('Сгибание на бицепс','4 × 10–20','upper',['Встань на середину ленты.','Локти прижаты к корпусу.']),ex('Скручивания с паузой','3 × 12–20','core',['Выдох на подъёме, поясница остаётся на полу.','Не тяни голову руками.']),ex('Hollow hold','3 × 20–40 сек','core',['Прижми поясницу к полу.','Если тяжело — согни колени.'])]},
  5:{title:'Верх тела: объём + пресс',sub:'Силовая • 50–60 минут',items:[ex('Медленные отжимания','4 × 8–15','push',['Опускание занимает 3 секунды.','Внизу короткая пауза, затем мощный подъём.']),ex('Отжимания с резинкой','3 × 6–15','push',['Лента за спиной, корпус жёсткий.']),ex('Жим резинки над головой','3 × 10–15','upper',['Корпус собран, не прогибай поясницу.']),ex('Тяга резинки в наклоне','4 × 12–20','row',['Локти веди к тазу.']),ex('Pull-apart','3 × 15–25','row',['Контролируй лопатки.']),ex('Обратные скручивания','3 × 12–20','core',['Подкручивай таз, медленно опускай.']),ex('RKC-планка','3 × 20–35 сек','core',['Сильно напряги пресс и ягодицы.'])]},
  6:{title:'Ноги + стабильный кор',sub:'Безопасная силовая • 45–55 минут',items:[ex('Мост с резинкой над коленями','4 × 15–25','glute',['Колени слегка давят наружу.','Таз двигается вверх без прогиба поясницы.']),ex('Румынская тяга с резинкой','4 × 12–15','glute',['Таз назад, шея нейтральна.']),ex('Вставание с высокого стула','3 × 10–15','glute',['Без боли в колене; амплитуда комфортна.']),ex('Отведение ноги с резинкой','3 × 15–20 / сторона','glute',['Двигай ногой, не наклоняя корпус.']),ex('Подъёмы на носки','4 × 20–25','glute',['Пауза в верхней точке.']),ex('Dead bug','3 × 10–12 / сторона','core',['Не отрывай поясницу.']),ex('Боковая планка','3 × 30–45 сек / сторона','core',['Ровная линия от плеча до стоп.'])]}
};
const foodDB={
 'Творог 5%':{k:121,p:17,f:5,c:3},'Яйца':{k:157,p:13,f:11,c:1},'Овсянка (сухая)':{k:370,p:13,f:7,c:60},'Банан':{k:89,p:1.1,f:.3,c:23},'Макароны (сухие)':{k:350,p:12,f:1.5,c:72},'Картофель (сырой)':{k:77,p:2,f:.1,c:17},'Куриное филе (сырое)':{k:113,p:23.6,f:1.9,c:0},'Говядина постная (сырая)':{k:187,p:18.9,f:12.4,c:0},'Овощи':{k:30,p:1.5,f:.2,c:5},'Масло растительное':{k:900,p:0,f:100,c:0},'Кефир 2.5%':{k:53,p:2.9,f:2.5,c:4},'Хлеб':{k:250,p:8,f:3,c:49}
};
function todayKey(){return new Date().toISOString().slice(0,10)}
function currentWorkout(){return workouts[new Date().getDay()]}
function renderWorkout(){const w=currentWorkout(), v=$('#workoutView'); if(!w){v.innerHTML=`<div class="hero"><div class="date">${new Date().toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'})}</div><h2>Восстановление</h2><p>Сон, питание, ходьба 30–45 минут и лёгкая мобильность. Это часть результата.</p></div><div class="rest"><h2>Сегодня без силовой</h2>Никакого чувства вины: мышцы и нервная система восстанавливаются именно сейчас.</div>`;return} const done=store.get('done-'+todayKey(),{});v.innerHTML=`<div class="hero"><div class="row"><div class="date">${new Date().toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'})}</div><span class="pill">МЕСЯЦ 1</span></div><h2>${w.title}</h2><p>${w.sub}. Оставляй 1–2 повтора в запасе. Боль в колене — стоп и отметь это в прогрессе.</p></div><div class="row section-title"><span>Упражнения</span><span class="pill">${Object.values(done).filter(Boolean).length}/${w.items.length}</span></div>${w.items.map((x,i)=>`<article class="exercise-card ${done[i] ? 'done' : ''}" data-ex="${i}"><img src="${images[x.img]}" alt="Техника: ${x.name}"><div><h3>${x.name}</h3><p>${x.sets}</p></div><input class="check" type="checkbox" data-check="${i}" ${done[i]?'checked':''} aria-label="Отметить выполненным"></article>`).join('')}<p class="tip">Нажми на карточку упражнения, чтобы открыть фото, технику и ключевые ошибки.</p>`;
 v.querySelectorAll('[data-check]').forEach(c=>c.onchange=e=>{const d=store.get('done-'+todayKey(),{});d[e.target.dataset.check]=e.target.checked;store.set('done-'+todayKey(),d);renderWorkout()});v.querySelectorAll('.exercise-card').forEach(card=>card.onclick=e=>{if(e.target.matches('input'))return;openExercise(w.items[card.dataset.ex])})}
function openExercise(x){const d=$('#exerciseModal');d.innerHTML=`<div class="modal-content"><button class="close">×</button><img src="${images[x.img]}" alt="${x.name}"><h2>${x.name}</h2><p><b>${x.sets}</b></p><ul>${x.cues.map(c=>`<li>${c}</li>`).join('')}</ul><p class="mini">Фото — визуальная подсказка. Если движение вызывает боль в колене, суставе или спине, прекрати его и зафиксируй это в разделе «Прогресс».</p></div>`;d.querySelector('.close').onclick=()=>d.close();d.showModal()}
function calcFood(){return store.get('food-'+todayKey(),[]).reduce((a,x)=>{const d=foodDB[x.name],m=x.g/100;for(const k in a)a[k]+=(d[k]||0)*m;return a},{k:0,p:0,f:0,c:0})}
function renderFood(){const v=$('#foodView'),items=store.get('food-'+todayKey(),[]),t=calcFood();const opt=Object.keys(foodDB).map(x=>`<option>${x}</option>`).join('');const macro=(x,n,target)=>`<div class="macro"><b>${Math.round(x)}</b><span>${n}</span><div class="meter"><i style="width:${Math.min(100,x/target*100)}%"></i></div></div>`;v.innerHTML=`<div class="hero"><div class="date">ПИТАНИЕ СЕГОДНЯ</div><h2>Цель: 2 800 ккал</h2><p>Белок 130–150 г. Не стремись к идеальной цифре: регулярность важнее.</p></div><div class="macro-grid">${macro(t.k,'ккал',2800)}${macro(t.p,'белок',140)}${macro(t.f,'жиры',75)}${macro(t.c,'углеводы',360)}</div><form class="food-form" id="foodForm"><b>Добавить продукт</b><label>Продукт</label><select id="foodName">${opt}</select><div class="form-row"><div><label>Вес, г</label><input id="foodGrams" type="number" min="1" value="150" required></div><div style="align-self:end"><button class="primary">Добавить</button></div></div></form><div class="section-title">Дневник</div>${items.length?items.map((x,i)=>{let d=foodDB[x.name],m=x.g/100;return `<div class="food-item"><div><b>${x.name}</b><br><small>${x.g} г · ${Math.round(d.k*m)} ккал · Б ${Math.round(d.p*m)} г</small></div><button class="delete" data-del="${i}" aria-label="Удалить">×</button></div>`}).join(''):'<p class="mini">Добавь завтрак, обед, ужин и перекус. Для точности пользуйся весами; макароны указывай сухими, мясо — сырым.</p>'}`;$('#foodForm').onsubmit=e=>{e.preventDefault();const a=store.get('food-'+todayKey(),[]);a.push({name:$('#foodName').value,g:+$('#foodGrams').value});store.set('food-'+todayKey(),a);renderFood()};v.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{let a=store.get('food-'+todayKey(),[]);a.splice(b.dataset.del,1);store.set('food-'+todayKey(),a);renderFood()})}
function renderProgress(){const v=$('#progressView'),data=store.get('progress',{});v.innerHTML=`<div class="hero"><div class="date">ЕЖЕНЕДЕЛЬНЫЙ КОНТРОЛЬ</div><h2>Измеряй, не гадай</h2><p>Заполняй раз в неделю утром: после туалета и до завтрака.</p></div><div class="progress-card"><b>Текущие показатели</b><label class="mini">Вес, кг</label><input id="weight" type="number" step="0.1" placeholder="75.0" value="${data.weight||''}"><label class="mini">Талия, см</label><input id="waist" type="number" step="0.5" placeholder="" value="${data.waist||''}"><label class="mini">Заметка о коленях / восстановлении</label><input id="note" placeholder="Например: без боли, сон 8 ч" value="${data.note||''}"><button class="primary" id="saveProgress">Сохранить</button></div><div class="notice"><b>Правило коленей.</b> Боль, отёк, блокировка или нестабильность — прекращай упражнение на ноги и обращайся к спортивному врачу/физиотерапевту. Не тренируйся через суставную боль.</div><div class="section-title">Напоминание</div><p class="mini">В разделе с колокольчиком можно включить уведомление во время открытого приложения или добавить надёжное ежедневное напоминание в календарь телефона.</p>`;$('#saveProgress').onclick=()=>{store.set('progress',{weight:$('#weight').value,waist:$('#waist').value,note:$('#note').value});alert('Сохранено')};}
function openReminder(){const d=$('#reminderModal');d.innerHTML=`<div class="modal-content"><button class="close">×</button><h2>Напоминание на 11:00</h2><div class="notice"><b>Важно:</b> GitHub Pages — статический хостинг. Он не может гарантированно прислать push-уведомление, если браузер полностью закрыт. Поэтому для надёжности добавь повторяющееся напоминание в календарь телефона.</div><div class="modal-actions"><button class="primary" id="permission">Включить уведомления в приложении</button><button class="secondary" id="calendar">Скачать напоминание для календаря</button></div><p class="mini">Уведомление в приложении сработает, когда PWA/браузер запущен. Календарь — надёжный ежедневный вариант на iPhone и Android.</p></div>`;d.querySelector('.close').onclick=()=>d.close();$('#permission').onclick=async()=>{if(!('Notification'in window))return alert('Браузер не поддерживает уведомления');const r=await Notification.requestPermission();if(r==='granted'){scheduleNotification();alert('Разрешение выдано. Когда приложение открыто, напомню в 11:00. Для фонового напоминания добавь календарь.')}else alert('Разрешение не выдано.')};$('#calendar').onclick=downloadICS;d.showModal()}
function scheduleNotification(){if(!('Notification'in window)||Notification.permission!=='granted')return;let now=new Date(),next=new Date();next.setHours(11,0,0,0);if(next<=now)next.setDate(next.getDate()+1);setTimeout(()=>{new Notification('Форма: время тренировки',{body:'Открой план и сделай сегодняшнюю тренировку.'});scheduleNotification()},next-now)}
function downloadICS(){const ics=`BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Forma//RU\nBEGIN:VEVENT\nUID:forma-training-1100\nDTSTAMP:20260729T000000Z\nDTSTART:20260730T110000\nRRULE:FREQ=DAILY\nSUMMARY:Форма — тренировка\nDESCRIPTION:Открой приложение «Форма» и выполни план дня.\nBEGIN:VALARM\nTRIGGER:-PT0M\nACTION:DISPLAY\nDESCRIPTION:Время тренировки\nEND:VALARM\nEND:VEVENT\nEND:VCALENDAR`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));a.download='forma-training-11-00.ics';a.click();URL.revokeObjectURL(a.href)}
$('.bottom-nav').onclick=e=>{const b=e.target.closest('.nav-item');if(!b)return;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===b.dataset.view))};$('#notifyBtn').onclick=openReminder;
renderWorkout();renderFood();renderProgress();scheduleNotification();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
